import os
import shutil
import pathlib
import django

# 1. Define paths
BASE_DIR = pathlib.Path(__file__).parent
DB_FILE = BASE_DIR / "db.sqlite3"
MIGRATIONS_DIR = BASE_DIR / "task_manager" / "migrations"

def reset_project():
    print("🚀 Starting DevFlow Reset...")

    # 2. Delete the SQLite database file
    if DB_FILE.exists():
        try:
            os.remove(DB_FILE)
            print("✅ Deleted: db.sqlite3")
        except PermissionError:
            print("❌ Error: Close your Django server before running this script!")
            return

    # 3. Clear all migration files (except __init__.py)
    if MIGRATIONS_DIR.exists():
        for file in MIGRATIONS_DIR.glob("*.py"):
            if file.name != "__init__.py":
                os.remove(file)
        print("✅ Cleared: task_manager/migrations/")

    # 4. Run Django Migrations
    print("\n🔨 Rebuilding Database Structure...")
    os.system("python manage.py makemigrations")
    os.system("python manage.py migrate")

    # 5. Bootstrap Django Environment to create data
    print("\n👤 Creating Admin and Test Data...")
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'devflow_core.settings')
    django.setup()
    
    from django.contrib.auth.models import User
    from task_manager.models import Task

    # Create Superuser
    User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
    print("✅ Superuser created (User: admin, Pass: admin123)")

    # Create a First Sample Task
    Task.objects.create(
        title="Welcome to DevFlow",
        description="This is a test task generated by your reset script!",
        complexity=3,
        estimated_hours=12.5,
        sub_tasks="1. Setup project\n2. Run reset script\n3. Enjoy AI features"
    )
    print("✅ Sample task created")

    print("\n✨ Reset Complete! Run 'python manage.py runserver' to start.")

if __name__ == "__main__":
    reset_project()